language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

env:
  global:
    - secure: aOiqRRhbGw+r7P1PleSNKk5JTkItW/tQBYBhxGdJ7gN9KvlBHEmBHNd5Yl8AuE5R9W27Eo/BgtXIu09EMuND8cLr92b1P1ru1ebQMM+2FburF1y4psZakecSWAMDlF+km/cdES/AzIJ7dI1Fc4dGE/zNMuLLYEKmSDtVMHXucaI=
    - secure: QRaXkP2OkP9KIwN/ifxclkKUhifeu2pGE6jEkNr/8kluxPDPplX3QtR/qwYzt6v24QsAW+rGvA0atB3yIiiWRrxxq3DcrV5v4xpc6ZoqFJYxVfnPqMGqDkh0pV1+6Z9RP9upP1ol3eOWnHPK0EHSH8sBAWENxE9k0WcilgjHxeo=

script:
  - cargo build --release --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc --verbose
  - cargo package --verbose

deploy:
  provider: releases
  api-key:
    secure: YUXdO4SZv3+Cm550DGc9WLYRWHaBC4LWYkJK2sbR+GjSkNSvKHfxOe0+pDzJGHNY+QOWKal37H6bCGmk43xHgwWExb0nZ+Vp1nJG/nUeTcglF4tYSX+GJQEOioj1YmaOai0NuJ1peDS8TZXYmbghMc4vnLUnYg7t4gQ3m8M/fVY=
  file: target/package/roaring-$TRAVIS_TAG.crate
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = beta"

after_deploy:
  - cargo publish --token "$CRATES_IO_TOKEN"
  - ./ci/save_credentials.sh "$GITHUB_TOKEN" "$TRAVIS_REPO_SLUG"
  - ./ci/publish_docs.sh "$TRAVIS_TAG"
